INSERT INTO book (titre, auteur, year, page, genre_id, site_id) VALUES
('Le monde s''effondre', 'Chinua Achebe', 1958, 596, (SELECT id FROM genre WHERE name="Magazine"), (SELECT id FROM site WHERE city="Roubaix")),
('Contes', 'Hans Christian Andersen', 1835, 871, (SELECT id FROM genre WHERE name="Science Fiction"), (SELECT id FROM site WHERE city="Armentières")),
('Orgueil et Préjugés', 'Jane Austen', 1813, 918, (SELECT id FROM genre WHERE name="Scolaire"), (SELECT id FROM site WHERE city="Armentières")),
('Le Père Goriot', 'Honoré de Balzac', 1835, 324, (SELECT id FROM genre WHERE name="BD"), (SELECT id FROM site WHERE city="Armentières")),
('Molloy', 'Samuel Beckett', 1951, 453, (SELECT id FROM genre WHERE name="Horreur"), (SELECT id FROM site WHERE city="Armentières")),
('Le Décaméron', 'Boccace', 1349, 406, (SELECT id FROM genre WHERE name="BD"), (SELECT id FROM site WHERE city="Lille")),
('Fictions', 'Jorge Luis Borges', 1944, 781, (SELECT id FROM genre WHERE name="Politique"), (SELECT id FROM site WHERE city="Roubaix")),
('Les Hauts de Hurle-Vent', 'Emily Brontë', 1847, 879, (SELECT id FROM genre WHERE name="BD"), (SELECT id FROM site WHERE city="Armentières")),
('L''Étranger', 'Albert Camus', 1942, 935, (SELECT id FROM genre WHERE name="Roman"), (SELECT id FROM site WHERE city="Lille")),
('Voyage au bout de la nuit', 'Louis-Ferdinand Céline', 1932, 541, (SELECT id FROM genre WHERE name="Romance"), (SELECT id FROM site WHERE city="Lille")),
('Don Quichotte', 'Miguel de Cervantes', 1605, 905, (SELECT id FROM genre WHERE name="Manga"), (SELECT id FROM site WHERE city="St Omer")),
('Les Contes de Canterbury', 'Geoffrey Chaucer', 1400, 735, (SELECT id FROM genre WHERE name="Fantasy"), (SELECT id FROM site WHERE city="Armentières")),
('Nostromo', 'Joseph Conrad', 1904, 126, (SELECT id FROM genre WHERE name="BD"), (SELECT id FROM site WHERE city="Roubaix")),
('La Divine Comédie', 'Dante Alighieri', 1300, 475, (SELECT id FROM genre WHERE name="Fantasy"), (SELECT id FROM site WHERE city="Armentières")),
('De grandes espérances', 'Charles Dickens', 1861, 812, (SELECT id FROM genre WHERE name="Scolaire"), (SELECT id FROM site WHERE city="Armentières")),
('Jacques le Fataliste', 'Denis Diderot', 1796, 469, (SELECT id FROM genre WHERE name="Fantasy"), (SELECT id FROM site WHERE city="St Omer")),
('Berlin Alexanderplatz', 'Alfred Döblin', 1929, 243, (SELECT id FROM genre WHERE name="Science Fiction"), (SELECT id FROM site WHERE city="Lille")),
('Crime et Châtiment', 'Fiodor Dostoïevski', 1866, 351, (SELECT id FROM genre WHERE name="Histoire"), (SELECT id FROM site WHERE city="Armentières")),
('L''Idiot', 'Fiodor Dostoïevski', 1869, 939, (SELECT id FROM genre WHERE name="Science Fiction"), (SELECT id FROM site WHERE city="Armentières")),
('Les Frères Karamazov', 'Fiodor Dostoïevski', 1880, 160, (SELECT id FROM genre WHERE name="Roman"), (SELECT id FROM site WHERE city="Roubaix")),
('Middlemarch', 'George Eliot', 1871, 913, (SELECT id FROM genre WHERE name="BD"), (SELECT id FROM site WHERE city="Roubaix")),
('Homme invisible, pour qui chantes-tu ?', 'Ralph Ellison', 1952, 160, (SELECT id FROM genre WHERE name="Biographie"), (SELECT id FROM site WHERE city="Roubaix")),
('Médée', 'Euripide', -431, 738, (SELECT id FROM genre WHERE name="Romance"), (SELECT id FROM site WHERE city="Lille")),
('Absalon, Absalon !', 'William Faulkner', 1936, 443, (SELECT id FROM genre WHERE name="Romance"), (SELECT id FROM site WHERE city="Armentières")),
('Le Bruit et la Fureur', 'William Faulkner', 1929, 694, (SELECT id FROM genre WHERE name="Biographie"), (SELECT id FROM site WHERE city="Roubaix")),
('Madame Bovary', 'Gustave Flaubert', 1857, 323, (SELECT id FROM genre WHERE name="Horreur"), (SELECT id FROM site WHERE city="Lille")),
('L''éducation sentimentale', 'Gustave Flaubert', 1869, 952, (SELECT id FROM genre WHERE name="Policier"), (SELECT id FROM site WHERE city="Lille")),
('Romancero Gitano', 'Federico Garcia Lorca', 1928, 182, (SELECT id FROM genre WHERE name="Science Fiction"), (SELECT id FROM site WHERE city="Lille")),
('Cent ans de solitude', 'Gabriel Garcia Marquez', 1967, 526, (SELECT id FROM genre WHERE name="Biographie"), (SELECT id FROM site WHERE city="St Omer")),
('L''Amour aux temps du choléra', 'Gabriel Garcia Marquez', 1985, 415, (SELECT id FROM genre WHERE name="Fantasy"), (SELECT id FROM site WHERE city="Armentières")),
('Faust', 'Johann Wolfgang von Goethe', 1808, 602, (SELECT id FROM genre WHERE name="Histoire"), (SELECT id FROM site WHERE city="St Omer")),
('Les Âmes mortes', 'Nicolas Gogol', 1842, 309, (SELECT id FROM genre WHERE name="Romance"), (SELECT id FROM site WHERE city="Roubaix")),
('Le Tambour', 'Günter Grass', 1959, 780, (SELECT id FROM genre WHERE name="Histoire"), (SELECT id FROM site WHERE city="Roubaix")),
('La Faim', 'Knut Hamsun', 1890, 123, (SELECT id FROM genre WHERE name="Politique"), (SELECT id FROM site WHERE city="Armentières")),
('Le Vieil Homme et la Mer', 'Ernest Hemingway', 1952, 798, (SELECT id FROM genre WHERE name="Horreur"), (SELECT id FROM site WHERE city="St Omer")),
('Iliade', 'Homère', -850, 454, (SELECT id FROM genre WHERE name="Magazine"), (SELECT id FROM site WHERE city="Roubaix")),
('Odyssée', 'Homère', -750, 411, (SELECT id FROM genre WHERE name="Politique"), (SELECT id FROM site WHERE city="Armentières")),
('Une maison de poupée', 'Henrik Ibsen', 1879, 234, (SELECT id FROM genre WHERE name="Fantasy"), (SELECT id FROM site WHERE city="St Omer")),
('Ulysse', 'James Joyce', 1922, 747, (SELECT id FROM genre WHERE name="Policier"), (SELECT id FROM site WHERE city="Armentières")),
('Le Procès', 'Franz Kafka', 1925, 661, (SELECT id FROM genre WHERE name="Policier"), (SELECT id FROM site WHERE city="Lille")),
('Le Château', 'Franz Kafka', 1926, 319, (SELECT id FROM genre WHERE name="Roman"), (SELECT id FROM site WHERE city="Armentières")),
('Les Misérables', 'Victor Hugo', 1862, 203, (SELECT id FROM genre WHERE name="Scolaire"), (SELECT id FROM site WHERE city="Lille")),
('Notre-Dame de Paris', 'Victor Hugo', 1831, 435, (SELECT id FROM genre WHERE name="Magazine"), (SELECT id FROM site WHERE city="Armentières")),
('Le Petit Prince', 'Antoine de Saint-Exupéry', 1943, 846, (SELECT id FROM genre WHERE name="Romance"), (SELECT id FROM site WHERE city="Armentières")),
('La Peste', 'Albert Camus', 1947, 672, (SELECT id FROM genre WHERE name="Science Fiction"), (SELECT id FROM site WHERE city="Armentières")),
('L''Écume des jours', 'Boris Vian', 1947, 129, (SELECT id FROM genre WHERE name="Manga"), (SELECT id FROM site WHERE city="Roubaix")),
('Bel-Ami', 'Guy de Maupassant', 1885, 599, (SELECT id FROM genre WHERE name="Fantasy"), (SELECT id FROM site WHERE city="St Omer")),
('Le Rouge et le Noir', 'Stendhal', 1830, 139, (SELECT id FROM genre WHERE name="Roman"), (SELECT id FROM site WHERE city="Armentières")),
('La Chartreuse de Parme', 'Stendhal', 1839, 632, (SELECT id FROM genre WHERE name="Scolaire"), (SELECT id FROM site WHERE city="Armentières")),
('Les Fleurs du mal', 'Charles Baudelaire', 1857, 273, (SELECT id FROM genre WHERE name="Scolaire"), (SELECT id FROM site WHERE city="Armentières")),
('Le Horla', 'Guy de Maupassant', 1887, 408, (SELECT id FROM genre WHERE name="Manga"), (SELECT id FROM site WHERE city="St Omer")),
('L''Assommoir', 'Émile Zola', 1877, 361, (SELECT id FROM genre WHERE name="Horreur"), (SELECT id FROM site WHERE city="Armentières")),
('Germinal', 'Émile Zola', 1885, 676, (SELECT id FROM genre WHERE name="Horreur"), (SELECT id FROM site WHERE city="Roubaix")),
('Thérèse Raquin', 'Émile Zola', 1867, 459, (SELECT id FROM genre WHERE name="Politique"), (SELECT id FROM site WHERE city="Roubaix")),
('L''Œuvre', 'Émile Zola', 1886, 912, (SELECT id FROM genre WHERE name="Histoire"), (SELECT id FROM site WHERE city="Lille")),
('La Fortune des Rougon', 'Émile Zola', 1871, 390, (SELECT id FROM genre WHERE name="Roman"), (SELECT id FROM site WHERE city="Armentières")),
('La Curée', 'Émile Zola', 1872, 924, (SELECT id FROM genre WHERE name="Manga"), (SELECT id FROM site WHERE city="St Omer")),
('Nana', 'Émile Zola', 1880, 189, (SELECT id FROM genre WHERE name="Manga"), (SELECT id FROM site WHERE city="Armentières")),
('Pot-Bouille', 'Émile Zola', 1882, 734, (SELECT id FROM genre WHERE name="Magazine"), (SELECT id FROM site WHERE city="Lille")),
('Au Bonheur des Dames', 'Émile Zola', 1883, 577, (SELECT id FROM genre WHERE name="Biographie"), (SELECT id FROM site WHERE city="Lille")),
('La Joie de vivre', 'Émile Zola', 1884, 378, (SELECT id FROM genre WHERE name="Science Fiction"), (SELECT id FROM site WHERE city="St Omer")),
('Le Rêve', 'Émile Zola', 1888, 645, (SELECT id FROM genre WHERE name="Manga"), (SELECT id FROM site WHERE city="St Omer")),
('La Bête humaine', 'Émile Zola', 1890, 790, (SELECT id FROM genre WHERE name="Biographie"), (SELECT id FROM site WHERE city="Lille")),
('L''Argent', 'Émile Zola', 1891, 808, (SELECT id FROM genre WHERE name="BD"), (SELECT id FROM site WHERE city="Roubaix")),
('La Débâcle', 'Émile Zola', 1892, 792, (SELECT id FROM genre WHERE name="Biographie"), (SELECT id FROM site WHERE city="Armentières")),
('Le Docteur Pascal', 'Émile Zola', 1893, 767, (SELECT id FROM genre WHERE name="Romance"), (SELECT id FROM site WHERE city="Lille")),
('Les Thibault', 'Roger Martin du Gard', 1922, 242, (SELECT id FROM genre WHERE name="BD"), (SELECT id FROM site WHERE city="St Omer")),
('La Condition humaine', 'André Malraux', 1933, 111, (SELECT id FROM genre WHERE name="Horreur"), (SELECT id FROM site WHERE city="Lille")),
('Le Silence de la mer', 'Vercors', 1942, 189, (SELECT id FROM genre WHERE name="Policier"), (SELECT id FROM site WHERE city="Roubaix")),
('La Promesse de l''aube', 'Romain Gary', 1960, 929, (SELECT id FROM genre WHERE name="Roman"), (SELECT id FROM site WHERE city="Armentières")),
('Éducation européenne', 'Romain Gary', 1945, 154, (SELECT id FROM genre WHERE name="Biographie"), (SELECT id FROM site WHERE city="Armentières")),
('Les Racines du ciel', 'Romain Gary', 1956, 455, (SELECT id FROM genre WHERE name="Policier"), (SELECT id FROM site WHERE city="Roubaix")),
('La Vie devant soi', 'Romain Gary', 1975, 316, (SELECT id FROM genre WHERE name="Politique"), (SELECT id FROM site WHERE city="Roubaix")),
('L''Élégance du hérisson', 'Muriel Barbery', 2006, 861, (SELECT id FROM genre WHERE name="Romance"), (SELECT id FROM site WHERE city="Lille")),
('Ensemble, c''est tout', 'Anna Gavalda', 2004, 101, (SELECT id FROM genre WHERE name="Romance"), (SELECT id FROM site WHERE city="Lille")),
('Je l''aimais', 'Anna Gavalda', 2002, 678, (SELECT id FROM genre WHERE name="Romance"), (SELECT id FROM site WHERE city="Roubaix")),
('La Consolante', 'Anna Gavalda', 2008, 269, (SELECT id FROM genre WHERE name="Biographie"), (SELECT id FROM site WHERE city="Roubaix")),
('L''Île des oubliés', 'Victoria Hislop', 2010, 692, (SELECT id FROM genre WHERE name="Science Fiction"), (SELECT id FROM site WHERE city="Roubaix")),
('Le Chardonneret', 'Donna Tartt', 2013, 808, (SELECT id FROM genre WHERE name="Biographie"), (SELECT id FROM site WHERE city="Roubaix")),
('La Vérité sur l''affaire Harry Quebert', 'Joël Dicker', 2012, 370, (SELECT id FROM genre WHERE name="Horreur"), (SELECT id FROM site WHERE city="Lille")),
('L''énigme du retour', 'Dany Laferrière', 2009, 302, (SELECT id FROM genre WHERE name="Romance"), (SELECT id FROM site WHERE city="St Omer")),
('Le Livre des Baltimore', 'Joël Dicker', 2015, 788, (SELECT id FROM genre WHERE name="Horreur"), (SELECT id FROM site WHERE city="Lille")),
('La disparition de Stephanie Mailer', 'Joël Dicker', 2018, 343, (SELECT id FROM genre WHERE name="Manga"), (SELECT id FROM site WHERE city="St Omer")),
('Le Mystère Henri Pick', 'David Foenkinos', 2016, 247, (SELECT id FROM genre WHERE name="Roman"), (SELECT id FROM site WHERE city="Armentières")),
('Charlotte', 'David Foenkinos', 2014, 535, (SELECT id FROM genre WHERE name="Science Fiction"), (SELECT id FROM site WHERE city="Armentières")),
('Vers la beauté', 'David Foenkinos', 2018, 176, (SELECT id FROM genre WHERE name="Fantasy"), (SELECT id FROM site WHERE city="Armentières")),
('Le Bureau des Jardins et des Étangs', 'Didier Decoin', 2017, 757, (SELECT id FROM genre WHERE name="Histoire"), (SELECT id FROM site WHERE city="Armentières")),
('La Tresse', 'Laetitia Colombani', 2017, 106, (SELECT id FROM genre WHERE name="Romance"), (SELECT id FROM site WHERE city="Lille")),
('Changer l''eau des fleurs', 'Valérie Perrin', 2018, 434, (SELECT id FROM genre WHERE name="Biographie"), (SELECT id FROM site WHERE city="Roubaix")),
('Les Oubliés du dimanche', 'Valérie Perrin', 2015, 732, (SELECT id FROM genre WHERE name="BD"), (SELECT id FROM site WHERE city="Armentières")),
('Trois', 'Valérie Perrin', 2021, 492, (SELECT id FROM genre WHERE name="Horreur"), (SELECT id FROM site WHERE city="St Omer")),
('Le Bal des folles', 'Victoria Mas', 2019, 820, (SELECT id FROM genre WHERE name="Manga"), (SELECT id FROM site WHERE city="St Omer")),
('Le Cerf-volant', 'Laetitia Colombani', 2021, 462, (SELECT id FROM genre WHERE name="Manga"), (SELECT id FROM site WHERE city="Lille")),
('Le Parfum', 'Patrick Süskind', 1985, 972, (SELECT id FROM genre WHERE name="Scolaire"), (SELECT id FROM site WHERE city="St Omer")),
('L''Homme qui voulait être heureux', 'Laurent Gounelle', 2008, 315, (SELECT id FROM genre WHERE name="Policier"), (SELECT id FROM site WHERE city="St Omer")),
('Le Jour où j''ai appris à vivre', 'Laurent Gounelle', 2014, 473, (SELECT id FROM genre WHERE name="Horreur"), (SELECT id FROM site WHERE city="Lille")),
('Les Dieux voyagent toujours incognito', 'Laurent Gounelle', 2011, 984, (SELECT id FROM genre WHERE name="Horreur"), (SELECT id FROM site WHERE city="Roubaix")),
('Et tu trouveras le trésor qui dort en toi', 'Laurent Gounelle', 2016, 819, (SELECT id FROM genre WHERE name="Politique"), (SELECT id FROM site WHERE city="Armentières")),
('La Vie est facile, ne t''inquiète pas', 'Agnès Martin-Lugand', 2015, 942, (SELECT id FROM genre WHERE name="Roman"), (SELECT id FROM site WHERE city="St Omer")),
('Les gens heureux lisent et boivent du café', 'Agnès Martin-Lugand', 2013, 426, (SELECT id FROM genre WHERE name="BD"), (SELECT id FROM site WHERE city="St Omer"));